// User
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_GROCERY_LISTS = 'FETCH_GROCERY_LISTS'
export const ADD_NEW_GROCERY_LIST_ID = 'ADD_NEW_GROCERY_LIST_ID'

// GroceryList
export const UPDATE_GROCERY_LIST = 'UPDATE_GROCERY_LIST'
export const CREATE_GROCERY_LIST = 'CREATE_GROCERY_LIST'
export const LOAD_GROCERY_LISTS = 'LOAD_GROCERY_LISTS'
export const DELETE_GROCERY_LIST = 'DELETE_GROCERY_LIST'
